sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true

install:
    - pip install tox codecov

script:
    - tox

after_success:
    - codecov
