db:
    image: postgres:latest
    environment:
        - DB_NAME=localshop
        - DB_USER=localshop
        - DB_PASS=shopping
    ports:
        - "5432"
    volumes:
        - ./docker-vol/postgresql:/var/lib/postgresql

web:
    build: .
    volumes:
        - ./docker-vol:/opt/localshop
    links:
        - db:db
    environment:
        - DJANGO_SECRET_KEY=a7d03faa0c054b3dba38b396bf3c7996
        - DATABASE_URL=postgresql://localshop:shopping@db/localshop
        - DJANGO_MEDIA_ROOT=/localshop/media
    ports:
        - "8000:8000"
    command: uwsgi --http 0.0.0.0:8000 --module localshop.wsgi --master --die-on-term


worker:
    build: .
    volumes:
        - ./docker-vol:/opt/localshop
    links:
        - db:db
    environment:
        - DJANGO_SECRET_KEY=a7d03faa0c054b3dba38b396bf3c7996
        - DATABASE_URL=postgresql://localshop:shopping@db/localshop
        - DJANGO_MEDIA_ROOT=/localshop/media
    entrypoint:
        localshop
    command:
        celery worker -B -E
