# Generated by Django 2.2.13 on 2020-06-12 12:04

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_package_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(db_index=True, max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_.]+\\Z'), 'Enter a valid package name consisting', 'invalid')]),
        ),
    ]
