# Generated by Django 2.2.13 on 2020-06-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_auto_20171116_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidr',
            options={},
        ),
        migrations.AlterModelOptions(
            name='credential',
            options={'ordering': ['-created']},
        ),
    ]
