name: main

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install tox
      run: pip install --upgrade setuptools tox==3.15.0
    - name: Run tests
      run: tox -e py
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: .coverage
        fail_ci_if_error: true
